import React, {PureComponent} from "react";
import PropTypes from "prop-types";
// import {View} from "react-native";
import {Container, Content, StyleProvider,View} from "native-base";

// module deps
import ResultHeader from "./ResultHeader";

export default class Result extends PureComponent {
  constructor(props) {
    super(props);

    this.state = {
      selected: "",
    };

    this._onValueChange = this._onValueChange.bind(this);
  }

  _onValueChange(value) {
    //this.state.selected = value;

    this.setState({
      selected: value
    });
    this.props.callbackFromParent(value);

  }

  render() {
    const cities = [
      {id: "Acura ILX", name: "Acura ILX"},
      {id: "Acura MDX", name: "Acura MDX"},
      {id: "Acura NSX", name: "Acura NSX"},
      {id: "Acura RDX", name: "Acura RDX"},
      {id: "Acura RLX", name: "Acura RLX"},
      {id: "Acura TLX", name: "Acura TLX"},
      {id: "Alfa Romeo 4C", name: "Alfa Romeo 4C"},
      {id: "Alfa Romeo Giulia", name: "Alfa Romeo Giulia"},
      {id: "Alfa Romeo Stelvio", name: "Alfa Romeo Stelvio"},
      {id: "Aston Martin DB11", name: "Aston Martin DB11"},
      {id: "Aston Martin DBS", name: "Aston Martin DBS"},
      {id: "Aston Martin Rapide", name: "Aston Martin Rapide"},
      {id: "Aston Martin Vanquish", name: "Aston Martin Vanquish"},
      {id: "Aston Martin Vantage", name: "Aston Martin Vantage"},
      {id: "Audi A3", name: "Audi A3"},
      {id: "Audi A4", name: "Audi A4"},
      {id: "Audi A5", name: "Audi A5"},
      {id: "Audi A6", name: "Audi A6"},
      {id: "Audi A7", name: "Audi A7"},
      {id: "Audi A8", name: "Audi A8"},
      {id: "Audi Q3", name: "Audi Q3"},
      {id: "Audi Q5", name: "Audi Q5"},
      {id: "Audi Q7", name: "Audi Q7"},
      {id: "Audi Q8", name: "Audi Q8"},
      {id: "Audi RS", name: "Audi RS"},
      {id: "Audi S3", name: "Audi S3"},
      {id: "Audi S4", name: "Audi S4"},
      {id: "Audi S5", name: "Audi S5"},
      {id: "Audi SQ5", name: "Audi SQ5"},
      {id: "Audi TT", name: "Audi TT"},
      {id: "Audi TT RS", name: "Audi TT RS"},
      {id: "Audi TTS Coupe", name: "Audi TTS Coupe"},
      {id: "Audi e-tron", name: "Audi e-tron"},
      {id: "Audi R8", name: "Audi R8"},
      {id: "BMW 2 Series", name: "BMW 2 Series"},
      {id: "BMW 3 Series", name: "BMW 3 Series"},
      {id: "BMW 4 Series", name: "BMW 4 Series"},
      {id: "BMW 5 Series", name: "BMW 5 Series"},
      {id: "BMW 6 Series", name: "BMW 6 Series"},
      {id: "BMW 7 Series", name: "BMW 7 Series"},
      {id: "BMW 8 Series", name: "BMW 8 Series"},
      {id: "BMW M", name: "BMW M"},
      {id: "BMW X", name: "BMW X1"},
      {id: "BMW X2", name: "BMW X2"},
      {id: "BMW X3", name: "BMW X3"},
      {id: "BMW X4", name: "BMW X4"},
      {id: "BMW X5", name: "BMW X5"},
      {id: "BMW X6", name: "BMW X6"},
      {id: "BMW X7", name: "BMW X7"},
      {id: "BMW Z4", name: "BMW Z4"},
      {id: "BMW i3", name: "BMW i3"},
      {id: "BMW i8", name: "BMW i8"},
      {id: "BYD e6", name: "BYD e6"},
      {id: "Bentley Bentayga", name: "Bentley Bentayga"},
      {id: "Bentley Mulsanne", name: "Bentley Mulsanne"},
      {id: "Bentley Chiron", name: "Bentley Chiron"},
      {id: "Buick Cascada", name: "Buick Cascada"},
      {id: "Buick Enclave", name: "Buick Enclave"},
      {id: "Buick Encore", name: "Buick Encore"},
      {id: "Buick Envision", name: "Buick Envision"},
      {id: "Buick LaCrosse", name: "Buick LaCrosse"},
      {id: "Buick Regal", name: "Buick Regal"},
      {id: "Cadillac ATS", name: "Cadillac ATS"},
      {id: "Cadillac CT6", name: "Cadillac CT6"},
      {id: "Cadillac CTS", name: "Cadillac CTS"},
      {id: "Cadillac Escalade", name: "Cadillac Escalade"},
      {id: "Cadillac XT4", name: "Cadillac XT4"},
      {id: "Cadillac XT5", name: "Cadillac XT5"},
      {id: "Cadillac XTS", name: "Cadillac XTS"},
      {id: "Cadillac XTS Hearse", name: "Cadillac XTS Hearse"},
      {id: "Cadillac Limo", name: "Cadillac Limo"},
      {id: "Cadillac XT6", name: "Cadillac XT6"},
      {id: "Chevrolet Blazer", name: "Chevrolet Blazer"},
      {id: "Chevrolet Bolt EV", name: "Chevrolet Bolt EV"},
      {id: "Chevrolet Camaro", name: "Chevrolet Camaro"},
      {id: "Chevrolet Colorado", name: "Chevrolet Colorado"},
      {id: "Chevrolet Corvette", name: "Chevrolet Corvette"},
      {id: "Chevrolet Cruze", name: "Chevrolet Cruze"},
      {id: "Chevrolet Equinox", name: "Chevrolet Equinox"},
      {id: "Chevrolet Impala", name: "Chevrolet Impala"},
      {id: "Chevrolet Malibu", name: "Chevrolet Malibu"},
      {id: "Chevrolet Silverado", name: "Chevrolet Silverado"},
      {id: "Chevrolet Sonic", name: "Chevrolet Sonic"},
      {id: "Chevrolet Spark", name: "Chevrolet Spark"},
      {id: "Chevrolet Suburban", name: "Chevrolet Suburban"},
      {id: "Chevrolet Tahoe", name: "Chevrolet Tahoe"},
      {id: "Chevrolet Traverse", name: "Chevrolet Traverse"},
      {id: "Chevrolet Trax", name: "Chevrolet Trax"},
      {id: "Chevrolet Volt", name: "Chevrolet Volt"},
      {id: "Chrysler 300", name: "Chrysler 300"},
      {id: "Chrysler Pacifica", name: "Chrysler Pacifica"},
      {id: "Dodge Challenger", name: "Dodge Challenger"},
      {id: "Dodge Charger", name: "Dodge Charger"},
      {id: "Dodge Durango", name: "Dodge Durango"},
      {id: "Dodge Grand Caravan", name: "Dodge Grand Caravan"},
      {id: "Dodge Journey", name: "Dodge Journey"},
      {id: "Ferrari 488 GTB", name: "Ferrari 488 GTB"},
      {id: "Ferrari 488 Pista", name: "Ferrari 488 Pista"},
      {id: "Ferrari 488 Pista Spider", name: "Ferrari 488 Pista Spider"},
      {id: "Ferrari 488 Spider", name: "Ferrari 488 Spider"},
      {id: "Ferrari 812 Superfast", name: "Ferrari 812 Superfast"},
      {id: "Ferrari GTC4Lusso", name: "Ferrari GTC4Lusso"},
      {id: "Ferrari Portofino", name: "Ferrari Portofino"},
      {id: "Fiat 124 Spider", name: "Fiat 124 Spider"},
      {id: "Fiat 500", name: "Fiat 500"},
      {id: "Fiat 500e", name: "Fiat 500e"},
      {id: "Ford EcoSport", name: "Ford EcoSport"},
      {id: "Ford Edge", name: "Ford Edge"},
      {id: "Ford Escape", name: "Ford Escape"},
      {id: "Ford Expedition", name: "Ford Expedition"},
      {id: "Ford Explorer", name: "Ford Explorer"},
      {id: "Ford F150", name: "Ford F150"},
      {id: "Ford Fiesta", name: "Ford Fiesta"},
      {id: "Ford Flex", name: "Ford Flex"},
      {id: "Ford Fusion", name: "Ford Fusion"},
      {id: "Ford GT", name: "Ford GT"},
      {id: "Ford Mustang", name: "Ford Mustang"},
      {id: "Ford Ranger", name: "Ford Ranger"},
      {id: "Ford Taurus", name: "Ford Taurus"},
      {id: "Ford Transit Connect", name: "Ford Transit Connect"},
      {id: "Ford Transit T150 Wagon", name: "Ford Transit T150 Wagon"},
      {id: "GMC Acadia", name: "GMC Acadia"},
      {id: "GMC Canyon", name: "GMC Canyon"},
      {id: "GMC Sierra", name: "GMC Sierra"},
      {id: "GMC Terrain", name: "GMC Terrain"},
      {id: "GMC Yukon", name: "GMC Yukon"},
      {id: "Genesis G70", name: "Genesis G70"},
      {id: "Genesis G80", name: "Genesis G80"},
      {id: "Genesis G90", name: "Genesis G90"},
      {id: "Honda Accord", name: "Honda Accord"},
      {id: "Honda CR-V", name: "Honda CR-V"},
      {id: "Honda Civic", name: "Honda Civic"},
      {id: "Honda Clarity", name: "Honda Clarity"},
      {id: "Honda Fit", name: "Honda Fit"},
      {id: "Honda HR-V", name: "Honda HR-V"},
      {id: "Honda Insight", name: "Honda Insight"},
      {id: "Honda Odyssey", name: "Honda Odyssey"},
      {id: "Honda Passport", name: "Honda Passport"},
      {id: "Honda Pilot", name: "Honda Pilot"},
      {id: "Honda Ridgeline", name: "Honda Ridgeline"},
      {id: "Hyundai Accent", name: "Hyundai Accent"},
      {id: "Hyundai Elantra", name: "Hyundai Elantra"},
      {id: "Hyundai Ioniq", name: "Hyundai Ioniq"},
      {id: "Hyundai Kona", name: "Hyundai Kona"},
      {id: "Hyundai Santa Fe", name: "Hyundai Santa Fe"},
      {id: "Hyundai Sonata", name: "Hyundai Sonata"},
      {id: "Hyundai Tucson", name: "Hyundai Tucson"},
      {id: "Hyundai Veloster", name: "Hyundai Veloster"},
      {id: "Infiniti Q50", name: "Infiniti Q50"},
      {id: "Infiniti Q60", name: "Infiniti Q60"},
      {id: "Infiniti Q70", name: "Infiniti Q70"},
      {id: "Infiniti QX30", name: "Infiniti QX30"},
      {id: "Infiniti QX50", name: "Infiniti QX50"},
      {id: "Infiniti QX60", name: "Infiniti QX60"},
      {id: "Infiniti QX80", name: "Infiniti QX80"},
      {id: "Jaguar E-Pace", name: "Jaguar E-Pace"},
      {id: "Jaguar F-Pace", name: "Jaguar F-Pace"},
      {id: "Jaguar F-Type", name: "Jaguar F-Type"},
      {id: "Jaguar I-Pace", name: "Jaguar I-Pace"},
      {id: "Jaguar XE", name: "Jaguar XE"},
      {id: "Jaguar XF", name: "Jaguar XF"},
      {id: "Jaguar XJ", name: "Jaguar XJ"},
      {id: "Jeep Cherokee", name: "Jeep Cherokee"},
      {id: "Jeep Compass", name: "Jeep Compass"},
      {id: "Jeep Grand Cherokee", name: "Jeep Grand Cherokee"},
      {id: "Jeep Renegade", name: "Jeep Renegade"},
      {id: "Jeep Wrangler", name: "Jeep Wrangler"},
      {id: "Jeep Gladiator", name: "Jeep Gladiator"},
      {id: "Kia Cadenza", name: "Kia Cadenza"},
      {id: "Kia Forte", name: "Kia Forte"},
      {id: "Kia K900", name: "Kia K900"},
      {id: "Kia Niro", name: "Kia Niro"},
      {id: "Kia Optima", name: "Kia Optima"},
      {id: "Kia Rio", name: "Kia Rio"},
      {id: "Kia Sedona", name: "Kia Sedona"},
      {id: "Kia Sorento", name: "Kia Sorento"},
      {id: "Kia Soul", name: "Kia Soul"},
      {id: "Kia Sportage", name: "Kia Sportage"},
      {id: "Kia Stinger", name: "Kia Stinger"},
      {id: "Kia Sedona", name: "Kia Sedona"},
      {id: "Kia Telluride", name: "Kia Telluride"},
      {id: "Lamborghini Aventador", name: "Lamborghini Aventador"},
      {id: "Lamborghini Huracan", name: "Lamborghini Huracan"},
      {id: "Lamborghini Urus", name: "Lamborghini Urus"},
      {id: "Land Rover Discovery", name: "Land Rover Discovery"},
      {id: "Land Rover Rang Rover", name: "Land Rover Rang Rover"},
      {id: "Land Rover Evoque", name: "Land Rover Evoque"},
      {id: "Lexus ES", name: "Lexus ES"},
      {id: "Lexus GS", name: "Lexus GS"},
      {id: "Lexus GX", name: "Lexus GX"},
      {id: "Lexus IS", name: "Lexus IS"},
      {id: "Lexus LC", name: "Lexus LC"},
      {id: "Lexus LS", name: "Lexus LS"},
      {id: "Lexus LX", name: "Lexus LX"},
      {id: "Lexus NX", name: "Lexus NX"},
      {id: "Lexus RC", name: "Lexus RC"},
      {id: "Lexus RX", name: "Lexus RX"},
      {id: "Lexus UX", name: "Lexus UX"},
      {id: "Lincoln Continental", name: "Lincoln Continental"},
      {id: "Lincoln MKC", name: "Lincoln MKC"},
      {id: "Lincoln MKT", name: "Lincoln MKT"},
      {id: "Lincoln MKZ", name: "Lincoln MKZ"},
      {id: "Lincoln Nautilus", name: "Lincoln Nautilus"},
      {id: "Lincoln Navigator", name: "Lincoln Navigator"},
      {id: "MINI Clubman", name: "MINI Clubman"},
      {id: "MINI Copper", name: "MINI Copper"},
      {id: "MINI Countryman", name: "MINI Countryman"},
      {id: "MINI John Cooper Works", name: "MINI John Cooper Works"},
      {id: "Maserati Ghibli", name: "Maserati Ghibli"},
      {id: "Maserati Eclipse Cross", name: "Maserati Eclipse Cross"},
      {id: "Maserati Mirage", name: "Maserati Mirage"},
      {id: "Maserati Outlander", name: "Maserati Outlander"},
      {id: "Nissan 370Z", name: "Nissan 370Z"},
      {id: "Nissan Altima", name: "Nissan Altima"},
      {id: "Nissan Armada", name: "Nissan Armada"},
      {id: "Subaru Ascent", name: "Subaru Ascent"},
      {id: "Toyota Corolla", name: "Toyota Corolla"},
      {id: "Toyota Sienna", name: "Toyota Sienna"},
    {id: "Toyota Supra", name: "Toyota Supra"},
    ];

    const {selected} = this.state;

    return (
          <ResultHeader
            handleSearchInput={this._searchCity}
            cities={cities}
            selected={selected}
            onValueChange={this._onValueChange}
          />
    );
  }
}

Result.propTypes = {
  cities: PropTypes.arrayOf(
    PropTypes.shape({
      id: PropTypes.string.isRequired,
      name: PropTypes.string.isRequired,
    }),
  ),
};
